### ISSUE TITLE
Issue with the Sodium implementation

### ISSUE THREAD

**Issue by BlockListed** [adamviola/BoostedBrightness#11]
Details:
Minecraft 1.16.5
Fabric 0.11.3
Fabric API 0.32.0+1.16
Sodium 0.1.0
BoostedBrightness 1.2.1
Starlight (Not sure if this matters pretty sure no) 0.0.2

I think this may cause a memory leak, as my memory usage exploded until I disabled it. But the logs don't seem that good anyway.
I also think this has something to do with Sodium.

Log:
https://paste.ee/p/2jkJc

**Comment by Bstn1802** [comment]
I dont see any reason for a memory leak although I have to admit I'm not an expert in that field. I found the reason for all those IllegalArgumentExceptions, I just didnt expect that exception to occur, I only thought of a ClassCastException and ignored it, now I coded it so that both exceptions shouldn't happen. By the way, I'm the one that added Sodium support for this mod.
I'm still not sure where the NullPointerException is coming from, and I'm not getting any errors at all which is weird.
Would be great if you could try out the mod with that fix I made and post your logs again. IllegalArgumentExceptions shouldn't occur anymore at all and NullPointerExceptions should print the full stack trace which will help me trying to figure out whats wrong there.
[boosted-brightness-1.2.2-beta.zip](https://github.com/adamviola/BoostedBrightness/files/6176011/boosted-brightness-1.2.2-beta.zip) (You need to change the ending from .zip to .jar)

**Comment by BlockListed** [comment]
I still have no idea where the memory leak. (I don't think minecraft should use 12 Gigs of ram when I allocated only 6 Gigs.) But it seems BB was not the issue, so I'm closing this.
