### ISSUE TITLE
BoostedBrightness seems to forget "normal" brightness.

### ISSUE THREAD

**Issue by Xrey274** [adamviola/BoostedBrightness#13]
Using Sodium btw. It seems that if I leave the game with Boosted Brightness on and then start the game again the mod has forgotten the "normal" brightness. Perhaps add a config option for what normal brightness should be.

**Comment by Bstn1802** [comment]
The mod should theoretically set the brightness back to normal when you close the game so that that is the one which will be saved in the options.txt. Im pretty sure that worked back when I implemented that in one of my pullrequests and the code is still there, let me test it real quick... Yep works fine for me. I basically set the brightness to the lowest possible, toggled to the brightest, quit the game (just closing the window) and when I started it it was back at -150%. Sodium shouldnt be affecting it at all and I was actually using it when testing it. How did you find out that it didnt work, how have you been testing it?

**Comment by Xrey274** [comment]
Closed the game with boosted brightness "on". I came back the next day and pressing 'B' did nothing, the boosted brightness remained. I had to manually reset the brightness to a "normal" level. Then the hotkey started turning it on or off.

**Comment by Bstn1802** [comment]
I dont see any reason why that could go wrong. In the code it toggles it back to normal right before the game is closing and it works for me. Did you test it multiple times? Which version are you using? Anything in the logs? Probably just spam because of the other issue lol.

**Comment by Xrey274** [comment]
Running 1.16.5 fabric multiple optimization mods. I'm using Starlight (mod that rewrites lighting engine), maybe they're related. I did test it multiple times, but it's very inconsistent. Sometimes it happens, other times not. I suggest you leave this issue open and I'll try to get a better idea as to how to recreate the problem.

**Comment by Xrey274** [comment]
I'm currently experiencing this problem. While it's like that do you need me to do something to potentially show what's causing it?

**Comment by Xrey274** [comment]
> I have also been experiencing this issue and have just figured what's going on. The trouble is that video settings aren't saved when minecraft is closed, so reverting the brightness at that point does nothing. The video setttings _are_ saved in these situations (checked by opening the options files and checking if writes happened since):
> 
>     * When the "Options" menu is closed.
> 
>     * When the "Video Settings" menu is opened.
> 
>     * When the "Video Settings" menu is closed.
> 
>     * Could be other times as well
> 
> 
> So here is a consistent way to reproduce the issue:
> 
>     1. Join a world.
> 
>     2. Enable boosted brightness
> 
>     3. Open & Close the Options menu.
>        
>        * Don't even change anything.
> 
>     4. Exit Minecraft
> 
> 
> The options file will now contain `gamma:12.0` instead of whatever "normal" brightness should be there.

Nice.

**Comment by Bstn1802** [comment]
I was waiting for an answer by the owner of this mod because I wanted to add some features and fix those issues here, but no response yet, so I just did it, why not
I made a pullrequest and you can download the draft release on my github. I dont know if this issue is fixed now since I never had that problem (same applies for the other issue) but I made a few changes and also theres a config file now so I am pretty sure things should get saved now. Btw because of the config, few other things changed as well and its not configurable in game yet.

**Comment by adamviola** [comment]
Just put out a new update that should resolve this issue!
