### ISSUE TITLE
Incompatible with a Mod combination of Sodium Shadowy Path Blocks and Reese Sodium Options

### ISSUE THREAD

**Issue by 2020Sanoj** [adamviola/BoostedBrightness#24]
When [Sodium Shadowy Path Blocks](https://www.curseforge.com/minecraft/mc-mods/sodium-shadowy-path-blocks) and [Reese Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options) are installed together with this Mod and the graphics screen is opened, minecraft crashes. (Maybe also the problem from #23 ?)
Without one of these three Mods, it is working. 
With only:
- Iris, Sodium, Sodium extra, Reese Sodium Options, Sodium Shadowy Path Blocks or 
- Iris, Sodium, Sodium extra, Reese Sodium Options, Boosted Brightness or 
- Iris, Sodium, Sodium extra, Boosted Brightness, Sodium Shadowy Path Blocks
it is working.

**Comment by Bstn1802** [comment]
Shouldn't be the same issue but could be similar. The crash report would be useful, but I'll try to reproduce it myself real quick. Great description as to how to reproduce btw although the individual mod versions could be helpful too. All of that would be listed in a crash report btw together with more info about the error.
_[some investigation later]_
I've been able to reproduce this error, but I'm pretty sure it has nothing to do with this mod. First of all, I'm getting the same crash report when I'm not using this mod (Boosted Brightness). And second, there's no mention of an error related to this mod in the crash report, but instead many errors relating to Reese Sodium Options (RSO) and Sodium Shadowy Path Blocks (SSPB).
I even investigated further and found the core issue being that SSPB is not using RSO correctly. I then checked the issues page for SSPB and found that there's already an issue open for that: https://github.com/Rynnavinx/sodium-shadowy-path-blocks/issues/6
The owner of RSO actually opened that issue because someone else opened an issue for that on the RSO issues page...
Anyway, again, I'm pretty sure it has nothing to do with this mod and that it's in the hands of the owner of SSPB to resolve this issue.
If you want you can check your four cases again (especially the first one of the three, since that _did_ crash for me) and a crash report would be really helpful then too if you can confirm those four cases again :)

**Comment by 2020Sanoj** [comment]
The crash report:
https://pb.san0j.de?7b8a0c9f3e032ec7#8SjrykWVgXFnULq4vGmh8xXfvtNHX5hdBZRxa2Dj77t9
But I think, it is Issue from SSPB, since after I updated all my Mods and tested it again it also crashes without Boosted Brightness. That's wired since before updating the mods it doesn't crash with SSSP and RSO, only when also Boosted Brightness was installed.
