### ISSUE TITLE
Incompatibility with Sodium Extra

### ISSUE THREAD

**Issue by GGamer6458** [adamviola/BoostedBrightness#25]
[crash-2022-05-27_06.06.17-client.txt](https://github.com/adamviola/BoostedBrightness/files/8783855/crash-2022-05-27_06.06.17-client.txt)

**Comment by Bstn1802** [comment]
Looks quite similar to other issues with sodium (-extra) that have been there before and since you're playing on an older version, 1.16.5, I assume those issues got fixed in a 1.17+ version, can't remember right now, but therefore it might be easy to fix, that is if the owner is willing to keep supporting 1.16
